### ISSUE TITLE
Can't <esc> out of select box focus

### ISSUE THREAD

**Issue by tremby** [vimperator/vimperator-labs#28]
When a `<select>` dropdown is focused and so we're in "insert" mode, `<esc>` isn't killing the focus and getting me back to normal mode. I have to grab the mouse and click somewhere to make it lose focus.

I'm on Mac OS X 10.8.5, Firefox 31, Vimperator 3.8.2.

**Comment by gkatsev** [comment]
Closing as fixed since #46 is fixed.

**Comment by tremby** [comment]
Sorry about that reference. I accidentally posted a link to this issue from a totally unrelated issue in an unrelated project!

I'll test this fix now.

**Comment by tremby** [comment]
Once a nightly lands, rather...

**Comment by gkatsev** [comment]
It's fixed in 3.9.

**Comment by tremby** [comment]
I'm running Vimperator 3.9 (2015-02-15), Firefox 36.0 and it is not fixed for me.

With a select box focussed, I press escape and I am still in INSERT mode with the select box focussed. I can't get out of that with the escape key.

**Comment by gkatsev** [comment]
Oh, sorry, it isn't in vimp 3.9. However, the fix should be available in master.
I'll try and get a nightly release out soon.

**Comment by gkatsev** [comment]
Actually, going to call #46 as the issue of truth.

**Comment by tremby** [comment]
This still pisses me off every single day. If this is indeed fixed in dev, please cut a release some time soon.

**Comment by tremby** [comment]
Still waiting.

**Comment by tremby** [comment]
Confirmed fixed.
