### ISSUE TITLE
QuickHints stopped working on some sites

### ISSUE THREAD

**Issue by philippm** [vimperator/vimperator-labs#415]
QuickHints (commands `f` and `F`) no longer show numbered items for some sites.

Sites that have stopped working include [DuckDuckGo](https://duckduckgo.com) and [Google](https://google.com) search results. Other sites such as [Stackoverflow](https://stackoverflow.com) and Github still work.

I'm running Firefox 44.0 on Mac OS X 10.11.3.

**Comment by bobf32** [comment]
Add BBC News and Feedly to the list of sites where only certain links get a quick hint shortcut,

**Comment by timss** [comment]
Seems to have been fixed by #409. 

>In the event a new release is not made or planned anytime soon, you may look into compiling it yourself, or link `{MY_FIREFOX_PROFILE}/extensions/vimperator@mozdev.org` to a clone of the repo.
>For more information, see http://www.vimperator.org/developerinfo

\- https://github.com/vimperator/vimperator-labs/pull/409#issuecomment-179986165

**Comment by philippm** [comment]
Thank you kindly -- I installed from source as per the link above and can confirm the issue is fixed there.

Any idea when there will be an official release?

**Comment by bobf32** [comment]
Not quite fixed I would say but a lot better. BBC news site now looking better, but left hand pane on feedly (category / folder list) still shows no links.

**Comment by timss** [comment]
@bobf32 It would be helpful if you provided a screenshot and/or url. I don't use Feedly, and other contributors might not either.

**Comment by senthilbaboo** [comment]
Added music.google.com to the list.

**Comment by bobf32** [comment]
![2016-02-12 09_04_50-zother - vimperator](https://cloud.githubusercontent.com/assets/6544564/13002628/dd2a9006-d167-11e5-9071-231fa641674a.png)

**Comment by timss** [comment]
If I had to guess I'd say it looks like an issue with `<iframe>`.

**Comment by bobf32** [comment]
i don't recall ever using it with vimperator before.

**Comment by timss** [comment]
In that case I don't think the issue is related to this one.

**Comment by hzzm** [comment]
Missing Hints 3.11.3 + FF-44.0.2: Win10 & linux-4.1.15 

First i noticed how the Hints were missing on google.com for the main menu that appears, after you yield the search results. Likewise the textinput's Hint is missing at that point. It didn't take long before i found other sites' menus also missing hints, including an ordinary website i coded myself.
I found a similar issue here on github, that indictes google had placed items with z-index: 199999999; or something, so i assigned a higher z-index to my hints, that didn't help either. Obviously i don't have that high z-indexes on my own site, so that shouldn't even be the problem.

The Win10 installation with FF-44.0.2 and Vimperator 3.11.3 has a clean vimperator, no .vimperatorrc.
Adjustments to the linux version's hints were made in .vimperatorrc, regardless the problem persisted before and after.
I disabled all addons except vimperator, the problem still persists.
I created a new linux FF profile and only installed a fresh vimperator, problem persists.

**Comment by smkr** [comment]
If there's a need for more testing sites RedHat Blog at https://www.redhat.com/en/about/blog not working for blog titles.
![screenshot_2016-02-25_14-29-55](https://cloud.githubusercontent.com/assets/4163323/13335090/70569e9c-dbcc-11e5-863a-cb5937953c44.png)

**Comment by timss** [comment]
As already mentioned, this seems to be fixed by #409. It was merged after 3.11.3 was released. I believe @gkatsev has been rather busy and haven't been able to ship a new release since then. If you don't feel like waiting, download latest from master.

**Comment by smkr** [comment]
timss: Thanks, just confirming that latest dev fixed it. Good job guys ;)

**Comment by timss** [comment]
@smkr Great to hear you got it working and we weren't facing yet another rogue z-index issue :-)

**Comment by timss** [comment]
Closing as confirmed fixed by #409, which is to be included in a later release.

Hints not working in `<iframe>` is a seperate issue, as mentioned.
