### ISSUE TITLE
:style* commands set is broken

### ISSUE THREAD

**Issue by ratijas** [vimperator/vimperator-labs#438]
`TypeError: array(...).flatten(...).uniq is not a function`

unfortunately, i'm not an addon developer; i don't even know where to look for traceback, otherwise i could do more useful ticket or PR. :)

Mac OS X 10.8.2,
vimperator 7eaba76,
FF 44.0.2

**Comment by timss** [comment]
Please include sample commands which you think is broken.

**Comment by ratijas** [comment]
```
:style -name spadict http://www.spanishdict.com/* .conj-match { border: 1px dashed red; }
:styletoggle -name spadict
:styleenable
```
it's like not constant behavior.  sometimes i get the error, and sometimes not.  however, eventually i was able to manage it to apply my styles; but still errors are weird to see.

**Comment by ratijas** [comment]
also, after `:delstyle -index …` i can't see deleted style in completitions for subsequent call `:delstyle` (expected), but i see it in the output list of `:style` (wtf).

**Comment by gkatsev** [comment]
The `array` typeerror makes sense and I believe it's fixed in master.
Last couple of weeks have been hectic at work but I should be able to find some time to release what we have over the weekend.

**Comment by timss** [comment]
Seems to be still present as of 3.12.0 on Firefox 44.0.1. Like @ratijas described, it doesn't seem to be constant.
