### ISSUE TITLE
Vimperator does not work with FF 47

### ISSUE THREAD

**Issue by cyber-duracel** [vimperator/vimperator-labs#441]
Plugin is installed 3.12 or 3.10pre (from nightly-fixup branch). The CLI on the bottom is just gray panel. Nothing in the terminal when I run FF from there. No error messages in the browser.

Please advise what further details are needed. With older FF 44 works like a charm.

Thank you

**Comment by timss** [comment]
Please see #398 as well. Although it may not be the cause for the gray panel, it's a likely milestone that needs to be checked off before Firefox 47 is to be supported properly.

Have you check if e10s is enabled? Please see #211.

**Comment by cyber-duracel** [comment]
@timss thanks for a swift response

- e10s is not enabled 
- #398 I don't understand a bit :) sorry

**Comment by reepush** [comment]
@cyber-duracel Try to build vimperator from [this branch](https://github.com/reepush/vimperator-labs/tree/comprehensions). I haven't tried it with 47, but with 46 it barely works.

**Comment by reepush** [comment]
@cyber-duracel Also you can you can comment about issues in 47 to #398. Probably they are caused by removing deprecated comprehensions.

**Comment by gkatsev** [comment]
Yeah, it definitely won't work because of the same reason that it wont work in firefox 46. Though, there's probably *other* stuff as well :)

**Comment by reepush** [comment]
@cyber-duracel Sad news. 47 is going to be released next monday as Developer Edition, so I will stuck with what you are experiencing now for sure.

**Comment by gkatsev** [comment]
Here's a list of all the possible changes slated for firefox 47: https://bugzilla.mozilla.org/buglist.cgi?resolution=---&query_format=advanced&target_milestone=47&target_milestone=Firefox%2047&target_milestone=mozilla47
Unfortunately, the compatibility report blogpost won't go up for a bit.

**Comment by gkatsev** [comment]
Not everything from that list is applicable but maybe something is.

**Comment by cyber-duracel** [comment]
I am using my distro's stable FF (iceweasel) 44.0.2, which is still OK, but sort of sluggish, but I suppose 46/47 is coming soon. May I help here somehow considering I am not a developer?

**Comment by timss** [comment]
If your Firefox is sluggish you may want to create a new profile. 

    $ iceweasel -no-remote -P

**Comment by MichaelRueegg** [comment]
I can confirm that Vimperator does not work in 47.0a2 as well (no error messages, but the Vimperator keys simply do not work). Also, the preference page is not properly shown:

![vimperator-settings-bug](https://cloud.githubusercontent.com/assets/206944/14672291/36aa499a-06f7-11e6-888a-3ac21647bc6b.png)

**Comment by gkatsev** [comment]
vimperator doesn't use the preferences pane, I think.

**Comment by reepush** [comment]
With 47 version I found only one issue so far – `Application` global object is undefined. It's used to get current version of Firefox and to open help instead of preferences popup.

Maybe someone knows more information about it? I didn't find any documentation as well as deprecation notices.

**Comment by msimonsson** [comment]
I updated to Firefox 46 just now and it's like Vimperator isn't installed, just a gray bar at the bottom of the window.

**Comment by elonwoo** [comment]
@msimonsson I updated to Firefox 46 and have the same problem

**Comment by gkatsev** [comment]
@msimonsson @elonwoo it's a known issue. Please see #398. Should be fixed this week, we'll take a look at firefox 47 afterwards.

**Comment by gineadai** [comment]
Firefox 47 is in Beta now, not in Nightly. Change title please.
@reepush
Yes `ReferenceError: Application is not defined` apper each time i press any command.
Couldn't open help `Sorry, help file "intro" not found`
`vimperator: Error sourcing macros directory: ReferenceError: io is not defined` common/content/liberator.js line 1869:17
`flags argument of String.prototype.{search,match,replace} is deprecated` common/content/liberator.js line 160:28
`mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create` common/content/liberator.js line 325:5
`NS_ERROR_FAILURE: Buffer<.URL()` common/content/buffer.js line 384
`NS_ERROR_FAILURE: updateUrl()` common/content/statusline.js line 303
`NS_ERROR_FAILURE: StatusField<.update()` common/content/statusline.js line 63
`NS_ERROR_FAILURE: updateField()` common/content/statusline.js line 221
`NS_ERROR_FAILURE: setOverLink()` common/content/buffer.js line 303

**Comment by gineadai** [comment]
Same errors in FF48 with e10s disabled +  warning only `expression closures are deprecated` in base.js:187:29.

**Comment by gineadai** [comment]
`ReferenceError: Application is not defined`
```
common/content/buffer.js:        if  (config.hostApplication == "Thunderbird") {
common/content/configbase.js:     * @property {Object} Application specific defaults for option values. The
common/content/configbase.js:    hostApplication: null,
common/content/io.js:        if (services.get("vc").compare(Application.version, "26.0a1") < 0) {
common/content/io.js:        if (services.get("vc").compare(Application.version, "26.0a1") < 0) {
common/content/io.js:            if (services.get("vc").compare(Application.version, "32") < 0) {
common/content/liberator.js:            window.goQuitApplication();
common/content/liberator.js:            "string", config.defaults.titlestring || config.hostApplication,
common/content/liberator.js:                                                     [config.hostApplication + ":", navigator.userAgent]]));
common/content/options.js:        let list = template.options(config.hostApplication + " Options", prefs());
common/content/options.js:                        commandline.input("Warning: Resetting all preferences may make " + config.hostApplication + " unusable. Continue (yes/[no]): ",
common/content/options.js:            context.title = [config.hostApplication + " Preference", "Value"];
common/content/preferences.xul:        Application.activeWindow.open(uri).focus(); // TODO: generalise for Muttator et al.
common/content/tabs.js:            }[config.hostApplication] || function () {};
common/content/tabs.js:        if (config.hostApplication === "Firefox")
common/content/util.js:        if (services.get("vc").compare(Application.version, "33") >= 0
muttator/content/config.js:    hostApplication: "Thunderbird",
muttator/content/config.js:            "Show " + config.hostApplication + " preferences",
muttator/install.rdf:        <em:targetApplication>
muttator/install.rdf:        </em:targetApplication>
vimperator/content/config.js:    hostApplication: "Firefox",
vimperator/content/config.js:            "Show " + config.hostApplication + " preferences",
vimperator/install.rdf:        <em:targetApplication>
vimperator/install.rdf:        </em:targetApplication>
```

**Comment by gkatsev** [comment]
So, the reason why we're getting the `Application is not defined` is because the FUEL library has been removed in firefox 47 after being deprecated since firefox 40. The `Application` object is loaded in by default. We've have to find alternatives and workarounds.
Everything that's changed: https://blog.mozilla.org/addons/2016/04/07/compatibility-for-firefox-47/

**Comment by gkatsev** [comment]
Should be fixed in master now.

**Comment by bedge** [comment]
Still seeing @ghost's comment #3 
Couldn't open help 

> Sorry, help file "intro" not found

with current release in firefox, 47.0b9 and vimperator 3.13.1

**Comment by bedge** [comment]
@MichaelRueegg's comment on the preferences not working is still broken in master@1cfe33f

**Comment by jayce-leathers** [comment]
I just updated to the stable release of FF 47 and am getting these same errors now. Anything I'm missing? Vimperator is 3.13.1

**Comment by gkatsev** [comment]
@jayce-leathers nope, I need to make a release of vimperator. Will be doing so tonight.

**Comment by gkatsev** [comment]
Made the release now. The review queue is a bit long not sure how quickly it'll go. I'll try and remember to update this thread when it goes through.

**Comment by wallydrag** [comment]
@gkatsev it is possible to update the add-on on our own, right?

**Comment by gkatsev** [comment]
There is a built XPI here: https://github.com/vimperator/vimperator-labs/releases/tag/vimperator-3.14.0 but it isn't signed. So, I'm not exactly sure how it works. It may be allowed to be installed as a temporary addon (one that's removed after the following restart or something) not exactly sure how that works.

**Comment by wallydrag** [comment]
@gkatsev it works, thanks. Since it is not yet signed, you need to go to _about:config_ and change _xpinstall.signatures.required_ to **false**

**Comment by gkatsev** [comment]
Yeah, though, that will be disabled in some version of stable firefox soon.

**Comment by toogy** [comment]
thanks for the quick fix @gkatsev :heart:

**Comment by greenmang0** [comment]
@wallydrag **about:config** hack is not needed anymore, Vimperator 3.14 update is now available. 
@gkatsev Thank you.

**Comment by kevincox** [comment]
Thanks, I just installed the update and everything appears to be working well.
