### ISSUE TITLE
Visual glitch with Vimperator and Firefox Test Pilot – Tab Center

### ISSUE THREAD

**Issue by bendiksolheim** [vimperator/vimperator-labs#509]
##### Issue type:

- Bug report

##### Version:

```
Vimperator: 3.13.0 (created: 2016/04/28 00:20:02)
Firefox:    Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:46.0) Gecko/20100101 Firefox/46.0
```

##### Description:

Firefox just launched something called [Test Pilot](https://testpilot.firefox.com/experiments), which is for testing out new features that might someday get into Firefox itself. One of these experiments is tab center, which places your tabs on the left instead of on the top. Vimperator does not seem to catch this, so when I open it the Vimperator GUI is behind the tabs on the left. It works just like normal, it is just not completely visible. Restarting Firefox does not fix this.

I realize that Test Pilot is a sort of beta testing, so issues should be expected. However, as this might someday end up in the Firefox core itself, I thought I'd report it anyway :)

##### Expected behavior:

Vimperator should be inside the viewport, and not behind parts of the window chrome. Alternatively, if easier to fix, it can be displayed above the tab center.

##### Steps to reproduce:

- Activate [Test Pilot](https://testpilot.firefox.com/experiments)
- Enable the [Tab Center](https://testpilot.firefox.com/experiments/tab-center) experiment
- Open Vimperator with something like `:version`
- Observe that the Vimperator is partially hidden behind Tab Center

**Comment by timss** [comment]
Thanks for the heads up. 

With Tree Style Tab this is solved using z-index. Somewhat related issues: 
- https://github.com/piroor/treestyletab/issues/586
- https://github.com/piroor/treestyletab/pull/843

**Comment by IsaacKhor** [comment]
z-index doesn't solve the issue; adding

```
.liberator-container, 
#liberator-bottombar {
	z-index: 100000000000000000000;
}
```

to userChrome.css doesn't change anything.

**Comment by darnir** [comment]
Is there any progress on this front? I would like to use the new Tab Center, but this glitch prevents me from doing so.

**Comment by timss** [comment]
Unfortunately no, no progress. Your best would be to try to tackle this issue yourself if you're able to, @darnir. Otherwise I recommend alternative addons such as tree style tab that do work.
