### ISSUE TITLE
Release New Version.

### ISSUE THREAD

**Issue by kevincox** [vimperator/vimperator-labs#605]
The current vimperator is fairly broken on current stable ff because auto-complete doesn't work. A new version should be released to fix this and include other updates.

Notable fixes:
- #559 
- #581 
- #591 
- #595 

Updates to addons are very seamless to users so there is very little reason not to release.

@gkatsev

**Comment by rr-** [comment]
The last time us pour souls that use Windows needed to rely for a user contributed build

**Comment by Karmaki** [comment]
Indeed, it would be great to have a new release soon. Many thanks in advance!

**Comment by gkatsev** [comment]
Done. Sorry for the long wait: https://github.com/vimperator/vimperator-labs/releases/tag/vimperator-3.15.0

**Comment by tobes** [comment]
@gkatsev 

mozilla is still showing version 3.14.0

https://addons.mozilla.org/en-GB/firefox/addon/vimperator/

**Comment by stepshal** [comment]
@tobes it's not reviewed by mozilla apparently, and it's release is lagging for me.

**Comment by gkatsev** [comment]
It's still in review on AMO. Nothing more we can do but wait for them to approve.

**Comment by rr-** [comment]
FYI you can try developer Firefox builds that allow to use unsigned extensions.

(IMHO it's absolutely preposterous for Mozilla to disable `xpinstall.signatures.required` in normal builds.)

**Comment by gkatsev** [comment]
It's up.
